begin;
create extension if not exists pgtap with schema extensions;
select plan(20);
select has_table('public','symbolic_birth_sources','symbolic birth sources are formal and versioned');
select has_table('public','symbolic_lens_preferences','symbolic preferences have one current owner state');
select has_table('public','symbolic_lens_snapshots','generated symbolic snapshots are separate from Reality');
select has_function('public','persist_symbolic_lens_v1',array['uuid','integer','uuid','text','jsonb','jsonb','text'],'symbolic save has a controlled atomic writer');
select has_function('public','withdraw_symbolic_lens_v1',array['uuid','integer','uuid','text'],'withdrawal has a controlled atomic writer');
select ok(coalesce((select relrowsecurity from pg_class where oid=to_regclass('public.symbolic_birth_sources')),false),'birth source storage enforces RLS');
select ok(coalesce((select relrowsecurity from pg_class where oid=to_regclass('public.symbolic_lens_preferences')),false),'preferences enforce RLS');
select ok(coalesce((select relrowsecurity from pg_class where oid=to_regclass('public.symbolic_lens_snapshots')),false),'snapshots enforce RLS');
select ok(not coalesce(has_table_privilege('anon',to_regclass('public.symbolic_birth_sources'),'SELECT'),true),'anon cannot read birth sources');
select ok(not coalesce(has_table_privilege('authenticated',to_regclass('public.symbolic_lens_snapshots'),'INSERT'),true),'browser cannot insert generated snapshots');
select ok(not coalesce(has_table_privilege('authenticated',to_regclass('public.symbolic_lens_preferences'),'UPDATE'),true),'browser cannot alter active consent pointers');
select ok(not coalesce(has_table_privilege('authenticated',to_regclass('public.symbolic_birth_sources'),'DELETE'),true),'browser cannot delete birth source versions');
select ok(not coalesce(has_function_privilege('authenticated',to_regprocedure('public.persist_symbolic_lens_v1(uuid,integer,uuid,text,jsonb,jsonb,text)'),'EXECUTE'),true),'browser cannot call the privileged save writer');
select ok(coalesce(has_function_privilege('service_role',to_regprocedure('public.persist_symbolic_lens_v1(uuid,integer,uuid,text,jsonb,jsonb,text)'),'EXECUTE'),false),'server service can call save writer');
select ok(coalesce((select not prosecdef from pg_proc where oid=to_regprocedure('public.persist_symbolic_lens_v1(uuid,integer,uuid,text,jsonb,jsonb,text)')),false),'symbolic writer is SECURITY INVOKER');
select has_function('public','recover_symbolic_lens_v1',array['uuid','integer','uuid','text','jsonb'],'HTTP retries can recover the owner receipt before recalculation');
select has_column('public','symbolic_lens_snapshots','trace_id','generated snapshots retain server writer trace');
select has_column('public','symbolic_lens_snapshots','writer_version','generated snapshots name their writer');
select has_column('public','symbolic_lens_snapshots','idempotency_key','generated snapshots bind request identity');
select has_column('public','symbolic_lens_snapshots','request_hash','hashes are identity only, never meaning drivers');
select * from finish();
rollback;
