begin;
create extension if not exists pgtap with schema extensions;
select plan(18);
select has_column('public','feedback_logs','version','canonical feedback is versioned');
select has_column('public','feedback_logs','writer_version','canonical feedback records its controlled writer');
select has_column('public','feedback_logs','idempotency_key','canonical feedback is owner-idempotent');
select has_column('public','feedback_logs','request_hash','feedback idempotency is content-bound');
select has_function('public','append_account_sandbox_feedback_m1',array['uuid','text','text','uuid'],'one append-only feedback RPC exists');
select ok(not (select prosecdef from pg_proc where oid=to_regprocedure('public.append_account_sandbox_feedback_m1(uuid,text,text,uuid)')),'feedback RPC is SECURITY INVOKER');
select function_privs_are('public','append_account_sandbox_feedback_m1',array['uuid','text','text','uuid'],'anon',array[]::text[],'anonymous cannot append feedback');
select function_privs_are('public','append_account_sandbox_feedback_m1',array['uuid','text','text','uuid'],'authenticated',array['EXECUTE'],'authenticated users enter only through the controlled feedback RPC');
select ok(not has_table_privilege('authenticated','public.feedback_logs','update'),'formal feedback cannot be updated by the browser');
select ok(not has_table_privilege('authenticated','public.feedback_logs','delete'),'formal feedback cannot be deleted by the browser');
select ok(has_table_privilege('authenticated','public.feedback_logs','insert'),'the controlled SECURITY INVOKER RPC retains its minimal append privilege');
select ok(exists(select 1 from pg_trigger where tgrelid=to_regclass('public.feedback_logs') and tgname='feedback_logs_m1_immutable_guard'),'formal feedback has a database immutability guard');
select ok(exists(select 1 from pg_indexes where schemaname='public' and tablename='feedback_logs' and indexname='feedback_logs_m1_owner_idempotency_unique'),'feedback idempotency is owner-scoped');
select ok(pg_get_functiondef('public.append_account_sandbox_feedback_m1(uuid,text,text,uuid)'::regprocedure) ilike '%auth.uid()%','feedback ownership derives from auth, never request input');
select ok(pg_get_functiondef('public.append_account_sandbox_feedback_m1(uuid,text,text,uuid)'::regprocedure) ilike '%status=''completed''%','feedback requires a completed formal Run');
select ok(pg_get_functiondef('public.append_account_sandbox_feedback_m1(uuid,text,text,uuid)'::regprocedure) ilike '%idempotency_key_content_conflict%','same key with changed feedback is rejected');
select ok((select count(*) from information_schema.tables where table_schema='public' and table_name in ('simulation_history','run_history','result_bundles'))=0,'History and Result reuse canonical simulations rather than parallel tables');
select ok(exists(select 1 from supabase_migrations.schema_migrations where version='20260830160000'),'formal API migration is recorded');
select * from finish();
rollback;
