import path from "node:path";
import { fileURLToPath } from "node:url";

import { defineConfig } from "vitest/config";

const projectRoot = path.dirname(fileURLToPath(import.meta.url));

export default defineConfig({
  resolve: {
    alias: {
      "@": path.resolve(projectRoot, "src"),
    },
  },
  test: {
    environment: "node",
    include: ["src/**/*.test.ts"],
    clearMocks: true,
    restoreMocks: true,
    coverage: {
      provider: "v8",
      include: [
        "src/lib/seed-context/storage.ts",
        "src/lib/people/extract.ts",
        "src/lib/agents/build.ts",
        "src/lib/relations/build.ts",
        "src/lib/simulation/branch-policy.ts",
        "src/lib/simulation/tick-policy.ts",
        "src/lib/simulation/edge-update-rules.ts",
        "src/lib/simulation/event-policy.ts",
        "src/lib/simulation/confidence-scoring.ts",
        "src/lib/simulation/simulation-engine.ts",
        "src/lib/claims/build.ts",
        "src/lib/reports/free-preview-policy.ts",
        "src/lib/reports/paid-report-policy.ts",
        "src/lib/reports/strategy-builder.ts",
        "src/lib/reports/report-engine.ts",
        "src/lib/safety/safety-rules.ts",
        "src/lib/safety/safety-verifier.ts",
        "src/lib/calibration/apply-feedback-to-next-run.ts",
        "src/lib/v2/reality-boundary/assumption-ledger.ts",
        "src/lib/v2/reality-boundary/evidence-ledger.ts",
        "src/lib/v2/reality-boundary/ids.ts",
        "src/lib/v2/reality-boundary/local-repository.ts",
        "src/lib/v2/reality-boundary/repository.ts",
        "src/lib/v2/reality-boundary/types.ts",
        "src/lib/v2/reality-boundary/v1-adapter.ts",
        "src/lib/v2/reality-boundary/validation.ts",
        "src/lib/v2/agent-world/action-proposal.ts",
        "src/lib/v2/agent-world/agent-definition.ts",
        "src/lib/v2/agent-world/agent-state.ts",
        "src/lib/v2/agent-world/ids.ts",
        "src/lib/v2/agent-world/types.ts",
        "src/lib/v2/agent-world/validation.ts",
        "src/lib/v2/agent-world/world-initializer.ts",
        "src/lib/v2/agent-world/world-transition.ts",
        "src/lib/v2/trajectory/ids.ts",
        "src/lib/v2/trajectory/local-adapter.ts",
        "src/lib/v2/trajectory/seeded-rng.ts",
        "src/lib/v2/trajectory/time.ts",
        "src/lib/v2/trajectory/trajectory-policy.ts",
        "src/lib/v2/trajectory/trajectory-runner.ts",
        "src/lib/v2/trajectory/types.ts",
        "src/lib/v2/trajectory/validation.ts",
        "src/lib/v2/trajectory-analysis/batch-runner.ts",
        "src/lib/v2/trajectory-analysis/child-run-spec.ts",
        "src/lib/v2/trajectory-analysis/clustering.ts",
        "src/lib/v2/trajectory-analysis/feature-extraction.ts",
        "src/lib/v2/trajectory-analysis/feature-integrity.ts",
        "src/lib/v2/trajectory-analysis/ids.ts",
        "src/lib/v2/trajectory-analysis/immutable.ts",
        "src/lib/v2/trajectory-analysis/intervention-comparison.ts",
        "src/lib/v2/trajectory-analysis/local-adapter.ts",
        "src/lib/v2/trajectory-analysis/pre-run-transition.ts",
        "src/lib/v2/trajectory-analysis/sensitivity.ts",
        "src/lib/v2/trajectory-analysis/simulation-frequency.ts",
        "src/lib/v2/trajectory-analysis/trajectory-result-validation.ts",
        "src/lib/v2/trajectory-analysis/types.ts",
        "src/lib/v2/trajectory-analysis/validation.ts",
        "src/lib/v2/claims-reports/claim-builder.ts",
        "src/lib/v2/claims-reports/ids.ts",
        "src/lib/v2/claims-reports/index.ts",
        "src/lib/v2/claims-reports/report-builder.ts",
        "src/lib/v2/claims-reports/stage5-revalidation.ts",
        "src/lib/v2/claims-reports/types.ts",
        "src/lib/v2/claims-reports/validation.ts",
        "src/lib/v2/outcome-calibration/backtesting.ts",
        "src/lib/v2/outcome-calibration/calibration.ts",
        "src/lib/v2/outcome-calibration/forecast-lock.ts",
        "src/lib/v2/outcome-calibration/ids.ts",
        "src/lib/v2/outcome-calibration/in-memory-repository.ts",
        "src/lib/v2/outcome-calibration/outcome-capture.ts",
        "src/lib/v2/outcome-calibration/repository.ts",
        "src/lib/v2/outcome-calibration/types.ts",
      ],
      reporter: ["text", "json-summary"],
      reportsDirectory: "coverage/v1-baseline",
      thresholds: {
        statements: 80,
        lines: 80,
        functions: 80,
        branches: 60,
      },
    },
  },
});
