"use client";

import { useEffect, useState } from "react";
import type { RealityProfileDraft } from "@/lib/reality-profile/profile";

const empty: RealityProfileDraft = { lifeClimate: { value: "", classification: "unknown", evidenceSummary: "明确未知" }, resources: { value: "", classification: "unknown", evidenceSummary: "明确未知" }, constraints: { value: "", classification: "unknown", evidenceSummary: "明确未知" }, revision: 0 };
const labels = { lifeClimate: "生活气候", resources: "资源", constraints: "限制" } as const;

export function RealityProfileClient() {
  const [profile, setProfile] = useState<RealityProfileDraft>(empty);
  const [status, setStatus] = useState("读取已保存资料…");
  const [ready, setReady] = useState(false);
  useEffect(() => { void fetch("/api/reality-profile", { cache: "no-store" }).then(async response => { const body = await response.json().catch(() => null) as { profile?: RealityProfileDraft | null; error_code?: string } | null; if (!response.ok) throw new Error(body?.error_code ?? "unavailable"); setProfile(body?.profile ?? empty); setStatus("逐项确认资料来源；未知项会保留为未知。"); setReady(true); }).catch(() => setStatus("无法读取资料。请确认已登录并已提交正式 Seed 后重试。")); }, []);
  const save = async () => { setStatus("正在安全保存…"); const response = await fetch("/api/reality-profile", { method: "PUT", headers: { "content-type": "application/json" }, body: JSON.stringify(profile) }); const body = await response.json().catch(() => null) as { profile?: RealityProfileDraft; error_code?: string } | null; if (response.ok && body?.profile) { setProfile(body.profile); setStatus("已保存到当前正式链。世界状态会只从这些已确认资料、锁定 Graph 与受控 Run 事件构建。"); return; } setStatus(body?.error_code === "reality_profile_conflict" ? "资料已在其他窗口更新。请刷新后再保存，避免覆盖。" : "保存未完成；当前表单仍保留，可检查后重试。"); };
  return <main id="main-content" className="mx-auto w-full max-w-4xl py-7 sm:py-12"><p className="font-mono text-xs uppercase tracking-[.14em] text-[var(--evidence-gold)]">Reality Profile / 当前正式链</p><h1 className="mt-4 text-3xl font-semibold text-[var(--text-primary)] sm:text-5xl">复核现实资料，而让系统保留不确定。</h1><p className="mt-4 max-w-2xl text-sm leading-7 text-[var(--text-secondary)]">填写简短、可复核的现实观察。每项都要标记为事实、假设或明确未知，请勿提交完整材料或敏感判断。</p><div className="mt-8 space-y-6">{(Object.keys(labels) as Array<keyof typeof labels>).map((key) => <section key={key} className="border-y border-white/10 py-5"><h2 className="text-xl font-semibold text-[var(--text-primary)]">{labels[key]}</h2><div className="mt-4 grid gap-4 md:grid-cols-2"><label className="text-sm text-[var(--text-secondary)]">资料类别<select disabled={!ready} value={profile[key].classification} onChange={event => setProfile({ ...profile, [key]: { value: event.target.value === "unknown" ? "" : profile[key].value, classification: event.target.value as RealityProfileDraft[typeof key]["classification"], evidenceSummary: event.target.value === "unknown" ? "明确未知" : profile[key].classification === "unknown" ? "" : profile[key].evidenceSummary } })} className="mt-2 block min-h-11 w-full border border-white/15 bg-black/20 px-3 text-[var(--text-primary)]"><option value="fact">事实</option><option value="assumption">假设</option><option value="unknown">明确未知</option></select></label><label className="text-sm text-[var(--text-secondary)]">安全证据摘要<textarea disabled={!ready || profile[key].classification === "unknown"} value={profile[key].evidenceSummary} onChange={event => setProfile({ ...profile, [key]: { ...profile[key], evidenceSummary: event.target.value } })} className="mt-2 block min-h-20 w-full border border-white/15 bg-black/20 px-3 py-2 text-[var(--text-primary)]" /></label></div><label className="mt-4 block text-sm text-[var(--text-secondary)]">可复核描述<textarea disabled={!ready || profile[key].classification === "unknown"} value={profile[key].value} onChange={event => setProfile({ ...profile, [key]: { ...profile[key], value: event.target.value } })} className="mt-2 block min-h-24 w-full border border-white/15 bg-black/20 px-3 py-2 text-[var(--text-primary)]" /></label></section>)}</div><button disabled={!ready} onClick={() => void save()} className="mt-7 min-h-11 rounded bg-[var(--evidence-gold)] px-5 py-3 text-sm font-semibold text-black disabled:opacity-50">保存当前正式链资料</button><p role="status" className="mt-4 text-sm leading-6 text-[var(--text-secondary)]">{status}</p></main>;
}
