import { NextResponse } from "next/server";
import { z } from "zod";
import { createSupabaseServerClient } from "@/lib/supabase/server";

const bodySchema = z.object({ selector: z.object({ seed_id: z.string().uuid() }).strict(), idempotency_key: z.string().uuid() }).strict();
const version = z.literal("phase3-graph-snapshot-v1"); const safety = z.enum(["safe", "caution"]);
const weight = z.number().int().min(0).max(100); const weights = z.object({ trust: weight, hostility: weight, dependency: weight, attraction: weight, competition: weight, information_gap: weight, resource_control: weight, emotional_debt: weight }).strict();
const evidence = z.union([z.literal("seed:submitted"), z.literal("key_person:confirmed"), z.literal("user_supplement"), z.string().regex(/^agent:[a-z_]+$/), z.string().regex(/^seed_context:[0-9a-f]{8}-(?:[0-9a-f]{4}-){3}[0-9a-f]{12}:[0-9a-f]{16}$/i)]);
const graph = z.object({ id: z.string().uuid(), agent_snapshot_id: z.string().uuid(), version, graph_locked: z.boolean(), locked_at: z.string().datetime({ offset: true }).nullable(), safety_level: safety, error_code: z.null() }).strip().superRefine((value, context) => {
  if (value.graph_locked !== (value.locked_at !== null)) context.addIssue({ code: z.ZodIssueCode.custom, message: "lock mismatch" });
});
const edge = z.object({ id: z.string().uuid(), graph_snapshot_id: z.string().uuid(), agent_snapshot_id: z.string().uuid(), from_agent_id: z.string().uuid(), to_agent_id: z.string().uuid(), version, relationship_type: z.enum(["professional", "personal", "family", "support", "competitive"]), weights, confidence: z.number().int().min(0).max(100), evidence_refs: z.array(evidence).min(1).max(32), safety_level: safety }).strip();
function trace() { return `graph_generate_${crypto.randomUUID()}`; } function fail(status: number, error_code: string, trace_id: string) { return NextResponse.json({ ok: false, error_code, trace_id }, { status }); }
function status(message: string): readonly [number, string] { if (message === "seed_not_found") return [404, message]; if (["agent_snapshot_invalid", "graph_snapshot_invalid", "graph_locked", "safety_downgraded", "safety_blocked", "idempotency_key_content_conflict"].includes(message)) return [409, message]; if (["evidence_required", "illegal_weight", "self_edge_forbidden"].includes(message)) return [400, message]; return [500, "persistence_failed"]; }
export async function POST(request: Request) { const trace_id = trace(); try { const supabase = await createSupabaseServerClient(); if (!supabase) return fail(500, "persistence_failed", trace_id); const { data: auth } = await supabase.auth.getUser(); if (!auth.user?.id) return fail(401, "unauthenticated", trace_id); if (request.headers.get("content-type")?.split(";", 1)[0]?.trim().toLowerCase() !== "application/json") return fail(400, "invalid_request", trace_id); const parsed = bodySchema.safeParse(await request.json().catch(() => null)); if (!parsed.success) return fail(400, "invalid_request", trace_id); const { data, error } = await supabase.rpc("generate_relation_graph_phase3", { p_seed_context_id: parsed.data.selector.seed_id, p_idempotency_key: parsed.data.idempotency_key }); if (error) { const [s,c] = status(error.message); return fail(s,c,trace_id); } if (!Array.isArray(data) || data.length !== 1 || !data[0] || typeof data[0] !== "object") return fail(500,"persistence_failed",trace_id); const row = data[0] as { idempotent?: unknown; graph?: unknown; edges?: unknown }; const g = graph.safeParse(row.graph); const es = z.array(edge).safeParse(row.edges); if (typeof row.idempotent !== "boolean" || !g.success || !es.success || es.data.length === 0 || es.data.some(e => e.graph_snapshot_id !== g.data.id || e.agent_snapshot_id !== g.data.agent_snapshot_id || e.safety_level !== g.data.safety_level || e.from_agent_id === e.to_agent_id)) return fail(500,"persistence_failed",trace_id); const pairs = new Set<string>(); if (es.data.some(e => { const p=[e.from_agent_id,e.to_agent_id].sort().join(":"); if(pairs.has(p)) return true; pairs.add(p); return false; })) return fail(500,"persistence_failed",trace_id); return NextResponse.json({ ok:true,error_code:null,idempotent:row.idempotent,graph:g.data,edges:es.data },{status:row.idempotent?200:201}); } catch { return fail(500,"persistence_failed",trace_id); } }
