import type {
  WriterPersistenceAuthorizationRemediationCategory,
  WriterPersistenceAuthorizationRemediationOwner,
} from "@/types/writer-persistence-authorization-remediation";
import type {
  WriterPersistenceAuthorizationReconsiderationRemediationReviewMode,
  WriterPersistenceAuthorizationReconsiderationRemediationReviewStatus,
} from "@/types/writer-persistence-authorization-reconsideration-remediation-review";

export type WriterPersistenceAuthorizationReconsiderationRemediationReviewNoGoMode =
  "persistence_adapter_implementation_authorization_reconsideration_remediation_review_no_go_packet_only";

export type WriterPersistenceAuthorizationReconsiderationRemediationReviewNoGoStatus =
  | "no_go_external_evidence_missing"
  | "manual_review_blocked";

export type WriterPersistenceAuthorizationReconsiderationRemediationReviewNoGoItem =
  {
    id: string;
    category: WriterPersistenceAuthorizationRemediationCategory;
    title: string;
    status: WriterPersistenceAuthorizationReconsiderationRemediationReviewNoGoStatus;
    owner: WriterPersistenceAuthorizationRemediationOwner;
    sourceReviewStatus: WriterPersistenceAuthorizationReconsiderationRemediationReviewStatus;
    sourceReviewItemIds: string[];
    sourceReconsiderationRemediationItemIds: string[];
    sourceNoGoItemIds: string[];
    sourcePreflightItemIds: string[];
    sourceOriginalRemediationItemIds: string[];
    sourceRefs: string[];
    noGoQuestion: string;
    noGoConclusion: string;
    blockingEvidence: string[];
    unresolvedReviewGaps: string[];
    forbiddenShortcuts: string[];
    finalDecisionPrerequisites: string[];
    safeEscalationRefs: string[];
    redactionRules: string[];
    nonAcceptanceClauses: string[];
    nextSafeAction: string;
  };

export type WriterPersistenceAuthorizationReconsiderationRemediationReviewNoGoRuntimeFlags =
  {
    allRuntimeEffectsBlocked: true;
    wouldAcceptReconsiderationRemediationReviewNoGo: false;
    wouldRecordReconsiderationRemediationReviewNoGo: false;
    wouldDenyImplementationAuthorizationFromReconsiderationReview: false;
    wouldPromoteToAuthorizationReconsideration: false;
    wouldAcceptReconsiderationRemediationReview: false;
    wouldRecordReconsiderationRemediationReview: false;
    wouldStoreReconsiderationRemediationReviewEvidence: false;
    wouldMarkReconsiderationExternalRemediationReviewed: false;
    wouldAcceptReconsiderationRemediation: false;
    wouldRecordReconsiderationRemediationEvidence: false;
    wouldMarkReconsiderationBlockerResolved: false;
    wouldCreateReconsiderationRemediationTicket: false;
    wouldAcceptReconsiderationNoGo: false;
    wouldRecordReconsiderationNoGo: false;
    wouldDenyImplementationAuthorizationFromReconsideration: false;
    wouldPromoteToReconsiderationRemediation: false;
    wouldAcceptReconsiderationPreflight: false;
    wouldRecordReconsiderationPreflight: false;
    wouldMarkReconsiderationReady: false;
    wouldStartAuthorizationReconsideration: false;
    wouldAcceptRemediationReviewNoGo: false;
    wouldRecordRemediationReviewNoGo: false;
    wouldAcceptRemediationReview: false;
    wouldRecordRemediationReview: false;
    wouldStoreRemediationReviewEvidence: false;
    wouldMarkExternalRemediationReviewed: false;
    wouldAcceptExternalRemediationState: false;
    wouldAcceptExternalApprovalArchive: false;
    wouldStoreApprovalArtifact: false;
    wouldUploadApprovalArtifact: false;
    wouldReadExternalArtifact: false;
    wouldHashExternalArtifact: false;
    wouldPersistArchiveIndex: false;
    wouldMarkArchiveComplete: false;
    wouldCreateAuthorizationRecord: false;
    wouldRecordAuthorizationDecision: false;
    wouldRecordAuthorizationNoGoDecision: false;
    wouldAcceptAuthorizationNoGoDecision: false;
    wouldDenyImplementationAuthorization: false;
    wouldGrantImplementationAuthorization: false;
    wouldRecordHumanDecision: false;
    wouldAcceptHumanDecision: false;
    wouldStoreDecisionArtifact: false;
    wouldAcceptReleaseNoGo: false;
    wouldRecordGoDecision: false;
    wouldGrantReleaseApproval: false;
    wouldEnableFeatureFlag: false;
    wouldDeployCode: false;
    wouldRunProductionWriter: false;
    wouldCollectSignature: false;
    wouldRecordOwnerApproval: false;
    wouldGrantImplementationApproval: false;
    wouldCreateApprovalRecord: false;
    wouldAcceptPatchReview: false;
    wouldReviewRealPatch: false;
    wouldAcceptPatch: false;
    wouldGeneratePatch: false;
    wouldApplyPatch: false;
    wouldModifyFiles: false;
    wouldCreateFiles: false;
    wouldDeleteFiles: false;
    wouldRunGitCommand: false;
    wouldCreateBranch: false;
    wouldCheckoutBranch: false;
    wouldCreatePullRequest: false;
    wouldCreateTestFiles: false;
    wouldRunAutomatedTests: false;
    wouldCreateImplementationPlan: false;
    wouldCreateImplementationBranch: false;
    wouldCreateAdapterCode: false;
    wouldImportRealWriterImplementation: false;
    wouldRunTransaction: false;
    wouldCreateServiceRoleClient: false;
    wouldReadServiceRoleSecret: false;
    wouldPersistEvidence: false;
    wouldStoreRawPayload: false;
    wouldStoreSecrets: false;
    wouldWriteRows: false;
    wouldWriteAuditRows: false;
    wouldReserveIdempotencyKeys: false;
    wouldWriteIdempotencyRows: false;
    wouldWriteCompensationRows: false;
    wouldCreateMigrationFile: false;
    wouldApplyMigration: false;
    wouldCreateTables: false;
    wouldEnableWriters: false;
    wouldCallAi: false;
    wouldCallStripe: false;
    wouldUnlockReports: false;
  };

export type WriterPersistenceAuthorizationReconsiderationRemediationReviewNoGoPayload =
  WriterPersistenceAuthorizationReconsiderationRemediationReviewNoGoRuntimeFlags & {
    safeMode: true;
    readOnly: true;
    reconsiderationRemediationReviewNoGoMode: WriterPersistenceAuthorizationReconsiderationRemediationReviewNoGoMode;
    sourceReconsiderationRemediationReviewChecklistMode: WriterPersistenceAuthorizationReconsiderationRemediationReviewMode;
    checkedAt: string;
    noGoItemCount: number;
    noGoCount: number;
    manualReviewBlockedCount: number;
    reconsiderationStillBlockedCount: number;
    blockingEvidenceCount: number;
    unresolvedReviewGapCount: number;
    forbiddenShortcutCount: number;
    finalDecisionPrerequisiteCount: number;
    sourceReviewItemCount: number;
    sourceExternalEvidenceMissingCount: number;
    sourceManualReviewerRequiredCount: number;
    sourceReconsiderationStillBlockedCount: number;
    reconsiderationRemediationReviewNoGoPacketReady: true;
    reconsiderationRemediationReviewNoGoPacketOnly: true;
    sourceReconsiderationRemediationReviewChecklistReady: true;
    sourceReconsiderationRemediationReviewChecklistOnly: true;
    sourceReconsiderationRemediationPlanReady: true;
    sourceReconsiderationRemediationPlanOnly: true;
    sourceReconsiderationNoGoPacketReady: true;
    sourceReconsiderationNoGoPacketOnly: true;
    sourcePreflightChecklistReady: true;
    sourcePreflightChecklistOnly: true;
    sourceReviewNoGoPacketReady: true;
    sourceReviewNoGoPacketOnly: true;
    sourceReleaseStillBlocked: true;
    preflightPassed: false;
    preflightAccepted: false;
    preflightRecorded: false;
    reconsiderationEligible: false;
    reconsiderationNoGoAccepted: false;
    reconsiderationNoGoRecorded: false;
    reconsiderationRemediationAccepted: false;
    reconsiderationRemediationRecorded: false;
    reconsiderationRemediationReviewAccepted: false;
    reconsiderationRemediationReviewRecorded: false;
    reconsiderationRemediationReviewComplete: false;
    reconsiderationRemediationReviewNoGoAccepted: false;
    reconsiderationRemediationReviewNoGoRecorded: false;
    implementationAuthorizationReconsiderationReady: false;
    implementationAuthorizationRemediationAccepted: false;
    implementationAuthorizationDecisionReady: false;
    implementationAuthorizationDecisionRecorded: false;
    implementationAuthorizationNoGoAccepted: false;
    implementationAuthorizationDenied: false;
    implementationAuthorizationGranted: false;
    implementationAuthorized: false;
    authorizationDecisionRecorded: false;
    authorizationArtifactStored: false;
    externalRemediationStatesAccepted: false;
    remediationReviewAccepted: false;
    remediationReviewComplete: false;
    remediationReviewNoGoAccepted: false;
    remediationReviewNoGoRecorded: false;
    externalApprovalArchiveAccepted: false;
    archiveCompletenessAccepted: false;
    implementationApprovalGranted: false;
    implementationBranchApproved: false;
    implementationPlanApproved: false;
    readyToApplyPatch: false;
    readyToCreateImplementationBranch: false;
    readyForAdapterImplementation: false;
    readyForReleaseExecution: false;
    adapterImplemented: false;
    adapterImplementationApproved: false;
    adapterImplementationAllowed: false;
    implementationReviewComplete: false;
    allOwnerApprovalsComplete: false;
    allBlockingEvidenceReady: false;
    blockedCodes: string[];
    reviewNoGoRules: string[];
    finalDecisionBoundaryRules: string[];
    sourceBlockedCodes: string[];
    noGoItems: WriterPersistenceAuthorizationReconsiderationRemediationReviewNoGoItem[];
  };

export type WriterPersistenceAuthorizationReconsiderationRemediationReviewNoGoProbeResult =
  WriterPersistenceAuthorizationReconsiderationRemediationReviewNoGoRuntimeFlags & {
    safeMode: true;
    readOnly: true;
    blocked: true;
    reconsiderationRemediationReviewNoGoMode: WriterPersistenceAuthorizationReconsiderationRemediationReviewNoGoMode;
    itemId?: string;
    itemTitle?: string;
    itemStatus?: WriterPersistenceAuthorizationReconsiderationRemediationReviewNoGoStatus;
    summary: string;
    reconsiderationRemediationReviewNoGoPacketOnly: true;
    sourceReconsiderationRemediationReviewChecklistOnly: true;
    sourceReconsiderationRemediationPlanOnly: true;
    sourceReconsiderationNoGoPacketOnly: true;
    sourcePreflightChecklistOnly: true;
    sourceReviewNoGoPacketOnly: true;
    sourceReleaseStillBlocked: true;
    preflightAccepted: false;
    preflightRecorded: false;
    reconsiderationEligible: false;
    reconsiderationNoGoAccepted: false;
    reconsiderationNoGoRecorded: false;
    reconsiderationRemediationAccepted: false;
    reconsiderationRemediationRecorded: false;
    reconsiderationRemediationReviewAccepted: false;
    reconsiderationRemediationReviewRecorded: false;
    reconsiderationRemediationReviewComplete: false;
    reconsiderationRemediationReviewNoGoAccepted: false;
    reconsiderationRemediationReviewNoGoRecorded: false;
    implementationAuthorizationReconsiderationReady: false;
    implementationAuthorizationGranted: false;
    implementationAuthorized: false;
    authorizationDecisionRecorded: false;
    authorizationArtifactStored: false;
    externalRemediationStatesAccepted: false;
    remediationReviewAccepted: false;
    remediationReviewComplete: false;
    remediationReviewNoGoAccepted: false;
    remediationReviewNoGoRecorded: false;
    externalApprovalArchiveAccepted: false;
    archiveCompletenessAccepted: false;
    readyToCreateImplementationBranch: false;
    readyForAdapterImplementation: false;
    readyForReleaseExecution: false;
    adapterImplemented: false;
    adapterImplementationApproved: false;
    adapterImplementationAllowed: false;
    allOwnerApprovalsComplete: false;
    allBlockingEvidenceReady: false;
    blockedCodes: string[];
    noGoItems: WriterPersistenceAuthorizationReconsiderationRemediationReviewNoGoItem[];
  };
