import type {
  WriterPersistenceAuthorizationRemediationCategory,
  WriterPersistenceAuthorizationRemediationOwner,
} from "@/types/writer-persistence-authorization-remediation";
import type {
  WriterPersistenceAuthorizationReconsiderationRemediationMode,
  WriterPersistenceAuthorizationReconsiderationRemediationStatus,
} from "@/types/writer-persistence-authorization-reconsideration-remediation";

export type WriterPersistenceAuthorizationReconsiderationRemediationReviewMode =
  "persistence_adapter_implementation_authorization_reconsideration_remediation_review_checklist_only";

export type WriterPersistenceAuthorizationReconsiderationRemediationReviewStatus =
  | "external_evidence_missing"
  | "manual_reviewer_required";

export type WriterPersistenceAuthorizationReconsiderationRemediationReviewItem =
  {
    id: string;
    category: WriterPersistenceAuthorizationRemediationCategory;
    title: string;
    status: WriterPersistenceAuthorizationReconsiderationRemediationReviewStatus;
    owner: WriterPersistenceAuthorizationRemediationOwner;
    sourceReconsiderationRemediationStatus: WriterPersistenceAuthorizationReconsiderationRemediationStatus;
    sourceReconsiderationRemediationItemIds: string[];
    sourceNoGoItemIds: string[];
    sourcePreflightItemIds: string[];
    sourceReviewItemIds: string[];
    sourceOriginalRemediationItemIds: string[];
    sourceRefs: string[];
    reviewQuestion: string;
    requiredExternalState: string;
    safeExternalEvidenceRefs: string[];
    completenessChecks: string[];
    redactionChecks: string[];
    rejectionTriggers: string[];
    nonAcceptanceClauses: string[];
    passCriteriaForFutureReview: string[];
    failCriteriaForCurrentReview: string[];
    stillBlockedBecause: string[];
    nextGate: string;
  };

export type WriterPersistenceAuthorizationReconsiderationRemediationReviewRuntimeFlags =
  {
    allRuntimeEffectsBlocked: true;
    wouldAcceptReconsiderationRemediationReview: false;
    wouldRecordReconsiderationRemediationReview: false;
    wouldStoreReconsiderationRemediationReviewEvidence: false;
    wouldMarkReconsiderationExternalRemediationReviewed: false;
    wouldPromoteToAuthorizationReconsideration: false;
    wouldAcceptReconsiderationRemediation: false;
    wouldRecordReconsiderationRemediationEvidence: false;
    wouldMarkReconsiderationBlockerResolved: false;
    wouldCreateReconsiderationRemediationTicket: false;
    wouldAcceptReconsiderationNoGo: false;
    wouldRecordReconsiderationNoGo: false;
    wouldDenyImplementationAuthorizationFromReconsideration: false;
    wouldPromoteToReconsiderationRemediation: false;
    wouldAcceptReconsiderationPreflight: false;
    wouldRecordReconsiderationPreflight: false;
    wouldMarkReconsiderationReady: false;
    wouldStartAuthorizationReconsideration: false;
    wouldAcceptRemediationReviewNoGo: false;
    wouldRecordRemediationReviewNoGo: false;
    wouldAcceptRemediationReview: false;
    wouldRecordRemediationReview: false;
    wouldStoreRemediationReviewEvidence: false;
    wouldMarkExternalRemediationReviewed: false;
    wouldAcceptExternalRemediationState: false;
    wouldAcceptExternalApprovalArchive: false;
    wouldStoreApprovalArtifact: false;
    wouldUploadApprovalArtifact: false;
    wouldReadExternalArtifact: false;
    wouldHashExternalArtifact: false;
    wouldPersistArchiveIndex: false;
    wouldMarkArchiveComplete: false;
    wouldCreateAuthorizationRecord: false;
    wouldRecordAuthorizationDecision: false;
    wouldRecordAuthorizationNoGoDecision: false;
    wouldAcceptAuthorizationNoGoDecision: false;
    wouldDenyImplementationAuthorization: false;
    wouldGrantImplementationAuthorization: false;
    wouldRecordHumanDecision: false;
    wouldAcceptHumanDecision: false;
    wouldStoreDecisionArtifact: false;
    wouldAcceptReleaseNoGo: false;
    wouldRecordGoDecision: false;
    wouldGrantReleaseApproval: false;
    wouldEnableFeatureFlag: false;
    wouldDeployCode: false;
    wouldRunProductionWriter: false;
    wouldCollectSignature: false;
    wouldRecordOwnerApproval: false;
    wouldGrantImplementationApproval: false;
    wouldCreateApprovalRecord: false;
    wouldAcceptPatchReview: false;
    wouldReviewRealPatch: false;
    wouldAcceptPatch: false;
    wouldGeneratePatch: false;
    wouldApplyPatch: false;
    wouldModifyFiles: false;
    wouldCreateFiles: false;
    wouldDeleteFiles: false;
    wouldRunGitCommand: false;
    wouldCreateBranch: false;
    wouldCheckoutBranch: false;
    wouldCreatePullRequest: false;
    wouldCreateTestFiles: false;
    wouldRunAutomatedTests: false;
    wouldCreateImplementationPlan: false;
    wouldCreateImplementationBranch: false;
    wouldCreateAdapterCode: false;
    wouldImportRealWriterImplementation: false;
    wouldRunTransaction: false;
    wouldCreateServiceRoleClient: false;
    wouldReadServiceRoleSecret: false;
    wouldPersistEvidence: false;
    wouldStoreRawPayload: false;
    wouldStoreSecrets: false;
    wouldWriteRows: false;
    wouldWriteAuditRows: false;
    wouldReserveIdempotencyKeys: false;
    wouldWriteIdempotencyRows: false;
    wouldWriteCompensationRows: false;
    wouldCreateMigrationFile: false;
    wouldApplyMigration: false;
    wouldCreateTables: false;
    wouldEnableWriters: false;
    wouldCallAi: false;
    wouldCallStripe: false;
    wouldUnlockReports: false;
  };

export type WriterPersistenceAuthorizationReconsiderationRemediationReviewPayload =
  WriterPersistenceAuthorizationReconsiderationRemediationReviewRuntimeFlags & {
    safeMode: true;
    readOnly: true;
    reconsiderationRemediationReviewChecklistMode: WriterPersistenceAuthorizationReconsiderationRemediationReviewMode;
    sourceReconsiderationRemediationMode: WriterPersistenceAuthorizationReconsiderationRemediationMode;
    checkedAt: string;
    reviewItemCount: number;
    externalEvidenceMissingCount: number;
    manualReviewerRequiredCount: number;
    reconsiderationStillBlockedCount: number;
    completenessCheckCount: number;
    redactionCheckCount: number;
    rejectionTriggerCount: number;
    sourceRemediationItemCount: number;
    sourceExternalRemediationRequiredCount: number;
    sourceManualReviewRequiredCount: number;
    sourceNoGoItemCount: number;
    sourceNoGoCount: number;
    sourceManualReviewBlockedCount: number;
    sourceReconsiderationStillBlockedCount: number;
    reconsiderationRemediationReviewChecklistReady: true;
    reconsiderationRemediationReviewChecklistOnly: true;
    sourceReconsiderationRemediationPlanReady: true;
    sourceReconsiderationRemediationPlanOnly: true;
    sourceReconsiderationNoGoPacketReady: true;
    sourceReconsiderationNoGoPacketOnly: true;
    sourcePreflightChecklistReady: true;
    sourcePreflightChecklistOnly: true;
    sourceReviewNoGoPacketReady: true;
    sourceReviewNoGoPacketOnly: true;
    sourceReleaseStillBlocked: true;
    preflightPassed: false;
    preflightAccepted: false;
    preflightRecorded: false;
    reconsiderationEligible: false;
    reconsiderationNoGoAccepted: false;
    reconsiderationNoGoRecorded: false;
    reconsiderationRemediationAccepted: false;
    reconsiderationRemediationRecorded: false;
    reconsiderationRemediationReviewAccepted: false;
    reconsiderationRemediationReviewRecorded: false;
    reconsiderationRemediationReviewComplete: false;
    implementationAuthorizationReconsiderationReady: false;
    implementationAuthorizationRemediationAccepted: false;
    implementationAuthorizationDecisionReady: false;
    implementationAuthorizationDecisionRecorded: false;
    implementationAuthorizationNoGoAccepted: false;
    implementationAuthorizationDenied: false;
    implementationAuthorizationGranted: false;
    implementationAuthorized: false;
    authorizationDecisionRecorded: false;
    authorizationArtifactStored: false;
    externalRemediationStatesAccepted: false;
    remediationReviewAccepted: false;
    remediationReviewComplete: false;
    remediationReviewNoGoAccepted: false;
    remediationReviewNoGoRecorded: false;
    externalApprovalArchiveAccepted: false;
    archiveCompletenessAccepted: false;
    implementationApprovalGranted: false;
    implementationBranchApproved: false;
    implementationPlanApproved: false;
    readyToApplyPatch: false;
    readyToCreateImplementationBranch: false;
    readyForAdapterImplementation: false;
    readyForReleaseExecution: false;
    adapterImplemented: false;
    adapterImplementationApproved: false;
    adapterImplementationAllowed: false;
    implementationReviewComplete: false;
    allOwnerApprovalsComplete: false;
    allBlockingEvidenceReady: false;
    blockedCodes: string[];
    reviewChecklistRules: string[];
    currentRejectionRules: string[];
    sourceBlockedCodes: string[];
    reviewItems: WriterPersistenceAuthorizationReconsiderationRemediationReviewItem[];
  };

export type WriterPersistenceAuthorizationReconsiderationRemediationReviewProbeResult =
  WriterPersistenceAuthorizationReconsiderationRemediationReviewRuntimeFlags & {
    safeMode: true;
    readOnly: true;
    blocked: true;
    reconsiderationRemediationReviewChecklistMode: WriterPersistenceAuthorizationReconsiderationRemediationReviewMode;
    itemId?: string;
    itemTitle?: string;
    itemStatus?: WriterPersistenceAuthorizationReconsiderationRemediationReviewStatus;
    summary: string;
    reconsiderationRemediationReviewChecklistOnly: true;
    sourceReconsiderationRemediationPlanOnly: true;
    sourceReconsiderationNoGoPacketOnly: true;
    sourcePreflightChecklistOnly: true;
    sourceReviewNoGoPacketOnly: true;
    sourceReleaseStillBlocked: true;
    preflightAccepted: false;
    preflightRecorded: false;
    reconsiderationEligible: false;
    reconsiderationNoGoAccepted: false;
    reconsiderationNoGoRecorded: false;
    reconsiderationRemediationAccepted: false;
    reconsiderationRemediationRecorded: false;
    reconsiderationRemediationReviewAccepted: false;
    reconsiderationRemediationReviewRecorded: false;
    reconsiderationRemediationReviewComplete: false;
    implementationAuthorizationReconsiderationReady: false;
    implementationAuthorizationGranted: false;
    implementationAuthorized: false;
    authorizationDecisionRecorded: false;
    authorizationArtifactStored: false;
    externalRemediationStatesAccepted: false;
    remediationReviewAccepted: false;
    remediationReviewComplete: false;
    remediationReviewNoGoAccepted: false;
    remediationReviewNoGoRecorded: false;
    externalApprovalArchiveAccepted: false;
    archiveCompletenessAccepted: false;
    readyToCreateImplementationBranch: false;
    readyForAdapterImplementation: false;
    readyForReleaseExecution: false;
    adapterImplemented: false;
    adapterImplementationApproved: false;
    adapterImplementationAllowed: false;
    allOwnerApprovalsComplete: false;
    allBlockingEvidenceReady: false;
    blockedCodes: string[];
    reviewItems: WriterPersistenceAuthorizationReconsiderationRemediationReviewItem[];
  };
