import "server-only";
import { NextResponse } from "next/server";
import { z } from "zod";
import { createSupabaseServerClient } from "@/lib/supabase/server";
import { getServiceRoleSupabaseClient } from "@/lib/supabase/service-role.server";
import { sandboxFailure,sandboxTrace } from "../http.server";
import { formalOutcomeInputSchema } from "./contracts";
import { readFormalOutcomes,saveFormalOutcome,readFormalCalibrationContext } from "./service.server";
async function caller(){const client=await createSupabaseServerClient();if(!client)return null;const {data,error}=await client.auth.getUser();return error||!data.user?.id||data.user.is_anonymous?null:{client,owner:data.user.id};}
function failed(error:unknown,trace:string){const code=error instanceof Error?error.message:"persistence_failed";if(code==="run_not_found")return sandboxFailure(404,code,trace);if(["invalid_target","invalid_observation","invalid_correction","not_observable","historical_lock_not_recorded","invalid_forecast_lock","invalid_reality_criteria","idempotency_key_content_conflict","outcome_already_recorded","invalid_observation_time","observation_window_open"].includes(code))return sandboxFailure(409,code,trace);return sandboxFailure(500,"persistence_failed",trace);}
function success(data:Record<string,unknown>,trace:string,status=200){return NextResponse.json({ok:true,error_code:null,trace_id:trace,...data},{status,headers:{"Cache-Control":"no-store"}});}
export async function outcomesHttp(request:Request,runId:string,write=false){const trace=sandboxTrace("outcomes");try{const context=await caller();if(!context)return sandboxFailure(401,"unauthenticated",trace);if(!z.string().uuid().safeParse(runId).success)return sandboxFailure(422,"invalid_request",trace);const service=getServiceRoleSupabaseClient();if(!service)return sandboxFailure(503,"persistence_unavailable",trace);if(!write)return success({outcomes:await readFormalOutcomes(service,context.owner,runId)},trace);if(request.headers.get("content-type")?.split(";")[0]?.trim().toLowerCase()!=="application/json")return sandboxFailure(422,"invalid_request",trace);const input=formalOutcomeInputSchema.safeParse(await request.json().catch(()=>null));if(!input.success)return sandboxFailure(422,"invalid_request",trace);const result=await saveFormalOutcome(service,context.owner,runId,input.data);return success(result,trace,result.idempotent?200:201);}catch(error){return failed(error,trace);}}
export async function calibrationContextHttp(request:Request){const trace=sandboxTrace("outcome_calibration");try{const context=await caller();if(!context)return sandboxFailure(401,"unauthenticated",trace);const url=new URL(request.url),params=[...url.searchParams.keys()];if(params.some(k=>k!=="graph_id")||url.searchParams.getAll("graph_id").length>1)return sandboxFailure(422,"invalid_request",trace);const graph=url.searchParams.get("graph_id")??undefined;if(graph&&!z.string().uuid().safeParse(graph).success)return sandboxFailure(422,"invalid_request",trace);const service=getServiceRoleSupabaseClient();if(!service)return sandboxFailure(503,"persistence_unavailable",trace);return success({context:await readFormalCalibrationContext(context.client,service,context.owner,graph)},trace);}catch(error){return failed(error,trace);}}
